{"level":"error","service_name":"MAIN","service_version":"0.0.1","service_id":"f1ad9c8a-e689-456b-9cfe-42ecbb2f942a","async_request_trace_id":"e10a10d2-760c-4a9d-b31b-e85f08e7dda2","url":"https://pruebas.app.sypago.net:8086/api/v1/auth/token","method":"POST","retries":2,"error":"Post \"https://pruebas.app.sypago.net:8086/api/v1/auth/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","timestamp":"2025-09-22T15:59:33.971617","message":"Error executing async request after retries"}
{"level":"error","service_name":"MAIN","service_version":"0.0.1","service_id":"e41acc4c-875b-4144-8f8f-482738fa4d1d","async_request_trace_id":"4ec8f99b-b312-4a9c-9135-834e7137484e","url":"https://pruebas.app.sypago.net:8086/api/v1/auth/token","method":"POST","retries":2,"error":"Post \"https://pruebas.app.sypago.net:8086/api/v1/auth/token\": dial tcp 127.0.0.1:8086: connect: connection refused","timestamp":"2025-09-23T13:29:41.749729","message":"Error executing async request after retries"}
